<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup><InternalsVisibleTo Include="MarketPulse.Tests" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../MarketPulse.Application/MarketPulse.Application.csproj" /><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
</Project>
